/* Danh sách hình cho trò Lật hình (ảnh trong assets/images/). nhom: con-vat | hoa | trai-cay */
const HINH_LAT = [
  { id: 'cho', ten: 'Chó con', nhom: 'con-vat' },
  { id: 'voi', ten: 'Con voi', nhom: 'con-vat' },
  { id: 'ga', ten: 'Con gà', nhom: 'con-vat' },
  { id: 'heo', ten: 'Con heo', nhom: 'con-vat' },
  { id: 'vit', ten: 'Con vịt', nhom: 'con-vat' },
  { id: 'tho', ten: 'Con thỏ', nhom: 'con-vat' },
  { id: 'chuot', ten: 'Chuột đầu bếp', nhom: 'con-vat' },
  { id: 'ngua', ten: 'Con ngựa', nhom: 'con-vat' },
  { id: 'khi', ten: 'Con khỉ', nhom: 'con-vat' },
  { id: 'ech', ten: 'Con ếch', nhom: 'con-vat' },
  { id: 'rua', ten: 'Con rùa', nhom: 'con-vat' },
  { id: 'ran', ten: 'Con rắn', nhom: 'con-vat' },
  { id: 'gau', ten: 'Con gấu', nhom: 'con-vat' },
  { id: 'huou', ten: 'Hươu cao cổ', nhom: 'con-vat' },
  { id: 'canh-cut', ten: 'Chim cánh cụt', nhom: 'con-vat' },
  { id: 'buom', ten: 'Con bướm', nhom: 'con-vat' },
  { id: 'ca-sau', ten: 'Cá sấu', nhom: 'con-vat' },
  { id: 'cua', ten: 'Con cua', nhom: 'con-vat' },
  { id: 'bach-tuoc', ten: 'Bạch tuộc', nhom: 'con-vat' },
  { id: 'cuu', ten: 'Con cừu', nhom: 'con-vat' },
  { id: 'de', ten: 'Con dê', nhom: 'con-vat' },
  { id: 'cao', ten: 'Con cáo', nhom: 'con-vat' },
  { id: 'bo-rua', ten: 'Bọ rùa', nhom: 'con-vat' },
  { id: 'ca', ten: 'Con cá', nhom: 'con-vat' },
  { id: 'oc-sen', ten: 'Ốc sên', nhom: 'con-vat' },
  { id: 'kien', ten: 'Con kiến', nhom: 'con-vat' },
  { id: 'soc', ten: 'Con sóc', nhom: 'con-vat' },
  { id: 'chim-xanh', ten: 'Chim xanh', nhom: 'con-vat' },
  { id: 'kangaroo', ten: 'Kangaroo', nhom: 'con-vat' },
  { id: 'koala', ten: 'Gấu koala', nhom: 'con-vat' },
  { id: 'gau-bac-cuc', ten: 'Gấu Bắc Cực', nhom: 'con-vat' },
  { id: 'hai-cau', ten: 'Hải cẩu', nhom: 'con-vat' },
  { id: 'rai-ca', ten: 'Rái cá', nhom: 'con-vat' },
  { id: 'nai', ten: 'Con nai', nhom: 'con-vat' },
  { id: 'linh-duong', ten: 'Linh dương', nhom: 'con-vat' },
  { id: 'lac-da', ten: 'Lạc đà', nhom: 'con-vat' },
  { id: 'trau', ten: 'Con trâu', nhom: 'con-vat' },
  { id: 'vet', ten: 'Con vẹt', nhom: 'con-vat' },
  { id: 'sau', ten: 'Sâu bướm', nhom: 'con-vat' },
  { id: 'ca-vang', ten: 'Cá vàng', nhom: 'con-vat' },
  { id: 'rua-bien', ten: 'Rùa biển', nhom: 'con-vat' },
  { id: 'lua', ten: 'Con lừa', nhom: 'con-vat' },
  { id: 'ngan', ten: 'Con ngỗng', nhom: 'con-vat' },
  { id: 'ga-tay', ten: 'Gà tây', nhom: 'con-vat' },
  { id: 'vet2', ten: 'Vẹt xanh', nhom: 'con-vat' },
  { id: 'cong', ten: 'Chim công', nhom: 'con-vat' },
  { id: 'hong-hac', ten: 'Hồng hạc', nhom: 'con-vat' },
  { id: 'thien-nga', ten: 'Thiên nga', nhom: 'con-vat' },
  { id: 'chim-se', ten: 'Chim sẻ', nhom: 'con-vat' },
  { id: 'go-kien', ten: 'Chim gõ kiến', nhom: 'con-vat' },
  { id: 'boi-ca', ten: 'Chim bói cá', nhom: 'con-vat' },
  { id: 'ca-map', ten: 'Cá mập', nhom: 'con-vat' },
  { id: 'ca-ngua', ten: 'Cá ngựa', nhom: 'con-vat' },
  { id: 'sao-bien', ten: 'Sao biển', nhom: 'con-vat' },
  { id: 'sua', ten: 'Con sứa', nhom: 'con-vat' },
  { id: 'ca-he', ten: 'Cá hề', nhom: 'con-vat' },
  { id: 'ca-duoi', ten: 'Cá đuối', nhom: 'con-vat' },
  { id: 'ca-kiem', ten: 'Cá kiếm', nhom: 'con-vat' },
  { id: 'ca-hoi', ten: 'Cá hồi', nhom: 'con-vat' },
  { id: 'tom', ten: 'Con tôm', nhom: 'con-vat' },
  { id: 'hen', ten: 'Con hến', nhom: 'con-vat' },
  { id: 'tac-ke', ten: 'Con tắc kè', nhom: 'con-vat' },
  { id: 'chuon-chuon', ten: 'Chuồn chuồn', nhom: 'con-vat' },
  { id: 'ky-da', ten: 'Con kỳ đà', nhom: 'con-vat' },
  { id: 'rua-can', ten: 'Rùa cạn', nhom: 'con-vat' },
  { id: 'chau-chau', ten: 'Châu chấu', nhom: 'con-vat' },
  { id: 'nhen', ten: 'Con nhện', nhom: 'con-vat' },
  { id: 'bo-cap', ten: 'Bọ cạp', nhom: 'con-vat' },
  { id: 'bo-canh-cung', ten: 'Bọ cánh cứng', nhom: 'con-vat' },
  { id: 'hoa-hong', ten: 'Hoa hồng', nhom: 'hoa' },
  { id: 'cuc', ten: 'Cúc họa mi', nhom: 'hoa' },
  { id: 'huong-duong', ten: 'Hoa hướng dương', nhom: 'hoa' },
  { id: 'sen', ten: 'Hoa sen', nhom: 'hoa' },
  { id: 'lan', ten: 'Lan hồ điệp', nhom: 'hoa' },
  { id: 'ly-ly', ten: 'Hoa ly', nhom: 'hoa' },
  { id: 'cam-tu-cau', ten: 'Cẩm tú cầu', nhom: 'hoa' },
  { id: 'mau-don-tim', ten: 'Mẫu đơn tím', nhom: 'hoa' },
  { id: 'mau-don-hong', ten: 'Mẫu đơn hồng', nhom: 'hoa' },
  { id: 'lavender', ten: 'Hoa lavender', nhom: 'hoa' },
  { id: 'tulip1', ten: 'Hoa tulip đỏ', nhom: 'hoa' },
  { id: 'tulip2', ten: 'Hoa tulip vàng', nhom: 'hoa' },
  { id: 'hoa-dau-tay', ten: 'Hoa dâu tây', nhom: 'hoa' },
  { id: 'hap-tinh', ten: 'Hoa tulip hồng', nhom: 'hoa' },
  { id: 'cay-tao', ten: 'Cây táo', nhom: 'trai-cay' },
  { id: 'cay-cam', ten: 'Cây cam', nhom: 'trai-cay' },
  { id: 'cay-chuoi', ten: 'Cây chuối', nhom: 'trai-cay' },
  { id: 'cay-dua', ten: 'Cây dừa', nhom: 'trai-cay' },
  { id: 'gian-nho', ten: 'Giàn nho', nhom: 'trai-cay' },
  { id: 'dau-tay', ten: 'Dâu tây', nhom: 'trai-cay' },
  { id: 'cay-xoai', ten: 'Cây xoài', nhom: 'trai-cay' },
  { id: 'cay-le', ten: 'Cây lê', nhom: 'trai-cay' },
  { id: 'cay-bo', ten: 'Cây bơ', nhom: 'trai-cay' },
  { id: 'cay-chanh', ten: 'Cây chanh', nhom: 'trai-cay' },
  { id: 'thanh-long', ten: 'Thanh long', nhom: 'trai-cay' },
  { id: 'gian-muop', ten: 'Giàn mướp', nhom: 'trai-cay' },
  { id: 'gian-bau', ten: 'Giàn bầu', nhom: 'trai-cay' },
  { id: 'cay-dao', ten: 'Cây đào', nhom: 'trai-cay' },
  { id: 'cay-man', ten: 'Cây mận', nhom: 'trai-cay' },
  { id: 'sau-rieng', ten: 'Sầu riêng', nhom: 'trai-cay' },
  { id: 'mang-cut', ten: 'Măng cụt', nhom: 'trai-cay' },
  { id: 'cay-quat', ten: 'Cây quất', nhom: 'trai-cay' },
  { id: 'dua-thom', ten: 'Quả dứa', nhom: 'trai-cay' },
  { id: 'dua-hau', ten: 'Dưa hấu', nhom: 'trai-cay' },
  { id: 'dua-luoi', ten: 'Dưa lưới', nhom: 'trai-cay' },
  { id: 'dau', ten: 'Quả dâu', nhom: 'trai-cay' },
  { id: 'viet-quat', ten: 'Việt quất', nhom: 'trai-cay' },
  { id: 'mam-xoi', ten: 'Mâm xôi', nhom: 'trai-cay' },
  { id: 'nho', ten: 'Chùm nho', nhom: 'trai-cay' },
  { id: 'qua-le', ten: 'Quả lê', nhom: 'trai-cay' },
  { id: 'ca-tim', ten: 'Cà tím', nhom: 'trai-cay' },
  { id: 'ca-chua', ten: 'Cà chua', nhom: 'trai-cay' },
  { id: 'dua-leo', ten: 'Dưa leo', nhom: 'trai-cay' },
  { id: 'ot', ten: 'Quả ớt', nhom: 'trai-cay' },
  { id: 'ot-chuong', ten: 'Ớt chuông đỏ', nhom: 'trai-cay' },
  { id: 'bi-ngo', ten: 'Bí ngô', nhom: 'trai-cay' },
  { id: 'hat-de', ten: 'Hạt dẻ', nhom: 'trai-cay' },
  { id: 'dau-phong', ten: 'Đậu phộng', nhom: 'trai-cay' },
  { id: 'hat-dieu', ten: 'Hạt điều', nhom: 'trai-cay' },
  { id: 'cu-cai', ten: 'Củ cải trắng', nhom: 'trai-cay' },
  { id: 'cu-den', ten: 'Củ dền', nhom: 'trai-cay' },
  { id: 'hanh-tay', ten: 'Hành tây', nhom: 'trai-cay' },
  { id: 'toi', ten: 'Củ tỏi', nhom: 'trai-cay' },
  { id: 'khoai-lang', ten: 'Khoai lang', nhom: 'trai-cay' },
  { id: 'xe', ten: 'Xe đua', nhom: 'khac' },
  { id: 'xe-tai', ten: 'Xe tải', nhom: 'khac' },
  { id: 'xe-cuu-hoa', ten: 'Xe cứu hỏa', nhom: 'khac' },
  { id: 'xe-cuu-thuong', ten: 'Xe cứu thương', nhom: 'khac' },
  { id: 'xe-canh-sat', ten: 'Xe cảnh sát', nhom: 'khac' },
  { id: 'taxi', ten: 'Xe taxi', nhom: 'khac' },
  { id: 'xe-jeep', ten: 'Xe jeep', nhom: 'khac' },
  { id: 'xe-dien', ten: 'Xe điện', nhom: 'khac' }
];
